
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test ./StoreTest
    - name: Restore dependencies
      run: dotnet restore ./Store.API/Store.API.csproj
    - name: Build
      run: dotnet build ./Store.API/Store.API.csproj --no-restore
